name: go_router_plus_example
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  go_router_plus:
    path: ../../go_router_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

dependency_overrides:
  go_router_plus:
    path: ../../go_router_plus

flutter:
  uses-material-design: true